baseURL = "https://get-pocket.netlify.com/"
languageCode = "en-us"
title = "My Get pocekt bookmarks"
disableKinds = ["section", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]
[params]
  homeText = "You just made a Hugo blog from scratch."
  colors = [ "white", "black", "light", "dark",  "primary", "link",  "info",  "success", "warning", "danger" ]
  # text_coors = [ "black", "white", "black", "white", "white",   "white", "white", "white",   "black",   "white" ]


